---
- hosts: server1
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: Add yum repository
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  # - name: add several packages
  #   yum:
  #     name: 
  #       - epel-release
  #       - wget
  #       - unzip
  #       - device-mapper-persistent-data
  #       - lvm2
  #       - docker-ce
  #       - docker-ce-cli
  #       - containerd.io
  #     state: present
  
  - name: optimal yum
    yum: 
      name: "{{ item }}"
      state: present
    loop:
      - epel-release
      - wget
      - unzip
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
      - docker-ce-cli
      - containerd.io
    register: echo
